### ISSUE TITLE
Clarify reasons why vulcan exists

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/vulcan#45]
Vulcan is not meant to be a hard "fork" of Prometheus.  From a conversation with @supershabam :

> right; I wonder if there’s a better tagline than `api-compatible alternative`
> it’s supposed to solve the long-term storage problem in parallel with prometheus

We should address this concern and clarify it in the README.

**Comment by fortytw2** [comment]
Perhaps something more along the lines of "Prometheus exten(ded|sion) for long term storage and high cardinality labels" could work well here

**Comment by supershabam** [comment]
Thanks @fortytw2, I like that.
