### ISSUE TITLE
Is there an estimated time of v0.1.0 version ?

### ISSUE THREAD

**Issue by geekard** [digitalocean/vulcan#90]
I'm a big fan of prometheus, and want to evaluate vulcan as a scalability and long-term storage solution. I saw version v0.1.0 will be a fully-functioning release. Do you guys have a estimated time ?

**Comment by supershabam** [comment]
I don't have an estimated time right now.

I'm taking a personal vacation and will be mostly AFK for a couple more weeks. I'll try and make an ETA once I'm back.

**Comment by geekard** [comment]
@supershabam 
any update ?

**Comment by supershabam** [comment]
@geekard sorry I forgot about this issue. I don't have an estimated time for v0.1.0 milestone.

relates to https://github.com/digitalocean/vulcan/issues/92
