### ISSUE TITLE
Is this project still activity?

### ISSUE THREAD

**Issue by geekard** [digitalocean/vulcan#92]
The most recent committing about code was Dec 6, 2016，what a long time!

Matthew Campbell had given a talking named 'Building Distributed Timeseries Database in GopherConIndia, the v2 timeseries table and final architecture are very different from this repo.
https://speakerdeck.com/mattkanwisher/building-distributed-timeseries-database-in-go

**Comment by supershabam** [comment]
Hi @geekard. It has indeed been a long time and there is still work to do. I've needed to focus on other tasks outside of Vulcan this quarter. @mattkanwisher (who gave the talk you referenced) has been working internally on different ways to write to and read from Cassandra to optimize for the specific real-world queries his team is doing and we're hoping to get that learning pushed up into Vulcan.

Thanks for your interest in the project. I foresee us adding more to Vulcan in April.
