### ISSUE TITLE
Does this project still be maintained?

### ISSUE THREAD

**Issue by Colstuwjx** [digitalocean/vulcan#95]
Hi team,

As prometheus version is updated to v1.7, and the v2.0 is also coming soon, does this project still be maintained?

As I known, prometheus [remote storage](https://www.robustperception.io/using-the-remote-write-path/) is a similar feature to make long-term storage available, how about integrate it with vulcan?

Thanks.

**Comment by allanliu** [comment]
Hey there,

Unfortunately this project is not maintained ATM, and there's no work planned for it in the immediate future.

Thanks.

**Comment by Colstuwjx** [comment]
Okay, thanks.
